[server]
port = 8503
address = "127.0.0.1"
enableCORS = false
enableXsrfProtection = false
headless = false
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8503

[theme]
base = "light"
primaryColor = "#1e6be6"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

